views/auth_view.py
#para tiempo de vencimiento
from datetime import timedelta

from flask import Blueprint, request, jsonify, make_response, render_template

#crear token
from flask_jwt_extended import(
    create_access_token,
    jwt_required,               #para saber si el usuario esta autenticado
    get_jwt,                    #para saber si el usuario es admin
)

#encriptar password
from werkzeug.security import (
    check_password_hash,
    generate_password_hash
)
from app import db
from models import User, Equipo

#importar schemas
from schemas import UserSchema

#autorizaciones de rutas
auth_bp = Blueprint('auth', __name__)

#crear token de login con post
@auth_bp.route('/login', methods=['POST'])
def login():
    data = request.authorization        #para saber la informacion del usuario
    username = data.username
    password = data.password

    usuario = User.query.filter_by(username=username).first()        #para saber si el usuario existe

    # si el usuario existe y coincide las contraseñas
    if usuario and check_password_hash(    #recibe contraseña hasheada y la contraseña del usuario
        pwhash = usuario.password_hash,
        password = password
    ):
        access_token = create_access_token(                     #para crear el token
            identity = username,                                #identidad del usuario
            expires_delta = timedelta(minutes=30),              #tiempo de expiración
            additional_claims=dict(                             #para saber si el usuario es admin
                administrador = usuario.is_admin
            )
        )
        #una ves ya creado el token, lo devolvemos
        return jsonify({'Token':f'Bearer {access_token}'})

    return jsonify(Mensaje ="El nombre de usuario o la contraseña son incorrectos")

#listar todos los usuarios
@auth_bp.route('/users', methods=['GET', 'POST'])
@jwt_required()  # Solo los usuarios autenticados pueden acceder
def users():
    additional_data = get_jwt()  # Obtener los datos del JWT para validar el rol
    administrador = additional_data.get('administrador', False)

    # Acción POST: Crear nuevo usuario solo si es administrador
    if request.method == 'POST':
        if administrador:
            data = request.get_json()  # Obtiene la información del usuario
            username = data.get('usuario')
            password = data.get('contrasenia')

            # Validar los datos antes de crear el usuario
            data_a_validar = dict(
                username=username,
                password_hash=password,
                is_admin=False
            )
            errors = UserSchema().validate(data_a_validar)
            if errors:
                return make_response(jsonify(errors))

            try:
                # Crear nuevo usuario
                nuevo_usuario = User(
                    username=username,
                    password_hash=generate_password_hash(password),
                    is_admin=False,
                )
                db.session.add(nuevo_usuario)
                db.session.commit()
                return jsonify(
                    {
                        "Mensaje": "Usuario creado",
                        "Usuario": nuevo_usuario.to_dict()
                    }
                )
            except Exception as e:
                return jsonify(
                    {
                        "Mensaje": "Fallo al crear el usuario",
                        "Error": str(e)
                    }
                )
        else:
            return jsonify(Mensaje="Solo el admin puede crear nuevos usuarios"), 403

    # Acción GET: Trae todos los usuarios
    if administrador:
        usuarios = User.query.all()  # Solo los administradores pueden ver todos los usuarios
        return UserSchema().dump(obj=usuarios, many=True)  # Devuelve todos los usuarios con más detalles
    else:
        return jsonify(Mensaje="No tiene permisos para ver los usuarios."), 403  # Si no es admin, denegar acceso

# Actualizar usuario
@auth_bp.route('/user/actualizar', methods=['PUT'])
@jwt_required()
def update_user():
    additional_data = get_jwt()
    administrador = additional_data['administrador']

    if not administrador:
        return jsonify({"Mensaje": "Solo un administrador puede actualizar usuarios."}), 403

    data = request.get_json()
    user_id = data.get("id")
    usuario = User.query.get_or_404(user_id)

    # Validamos y actualizamos los datos del usuario
    username = data.get('usuario', usuario.username)  # Si no se pasa un nuevo username, se mantiene el actual
    password = data.get('contrasenia')
    activo = data.get('activo', usuario.activo)  # Si no se pasa un nuevo valor, se queda con el actual

    if password:
        usuario.password_hash = generate_password_hash(password)
    usuario.username = username
    usuario.activo = activo  # Actualizamos el estado activo del usuario

    # Guardar cambios
    db.session.commit()

    return make_response(usuario.to_dict(), 200)

# Eliminar usuario
@auth_bp.route('/user/eliminar', methods=['DELETE'])
@jwt_required()
def delete_user():
    additional_data = get_jwt()
    administrador = additional_data.get('administrador', False)

    if not administrador:
        return jsonify(Mensaje="Solo un administrador puede eliminar usuarios"), 403

    # Leer el 'id' del cuerpo de la solicitud (JSON)
    data = request.get_json()
    usuario_id = data.get('id')

    if not usuario_id:
        return jsonify({"Mensaje": "Falta el parámetro 'id' en la solicitud."}), 400

    usuario = User.query.get_or_404(usuario_id)  # Buscar el usuario por el ID

    # Desactivar al usuario (marcar como inactivo)
    usuario.activo = 0  # Usamos 0 para marcar como inactivo
    db.session.commit()

    return jsonify(Mensaje="Usuario desactivado exitosamente"), 200


# Inicio
@auth_bp.route('/')
def index():
    equipos = Equipo.query.all()
    return render_template('index.html', equipos=equipos)

views/equipo_view.py
from flask import Blueprint, request, jsonify, make_response

from app import db
from models import Equipo

from schemas import EquipoSchema , EquipoMinimalSchema

from flask_jwt_extended import(
    jwt_required,               #para saber si el usuario esta autenticado
    get_jwt,                    #para saber si el usuario es admin
)

equipo_bp = Blueprint('equipo', __name__)

@equipo_bp.route("/equipos", methods=["GET"])
@jwt_required()  
def equipos():
    additional_data = get_jwt() 
    administrador = additional_data.get("administrador", False)  

    equipos = Equipo.query.all()  
    if administrador: 
        return EquipoSchema().dump(equipos, many=True) 
    else:  
        return EquipoMinimalSchema().dump(equipos, many=True)  

@equipo_bp.route("/equipos/crear", methods=["POST"])
@jwt_required()
def crear_equipo():
    additional_data = get_jwt()
    administrador = additional_data.get("administrador", False)

    if request.method == "POST":
        if administrador:
            data = request.get_json()  # Obtener los datos enviados en formato JSON
            
            # Validar el valor de 'activo' (0 o 1)
            activo = data.get("activo", 1)
            if activo not in [0, 1]:
                return jsonify({"Mensaje": "El valor de 'activo' debe ser 0 o 1."}), 400

            # Crear una nueva instancia del equipo usando los datos proporcionados
            nuevo_equipo = Equipo(
                nombre=data.get("nombre"),
                modelo_id=data.get("modelo_id"),
                categoria_id=data.get("categoria_id"),
                costo=data.get("costo"),
                stock_id=data.get("stock_id"),
                activo=activo,  # Establecer 'activo' como 1 o 0 según la validación
                marca_id=data.get("marca_id"),
            )  

            # Agregar el nuevo equipo a la sesión de la base de datos
            db.session.add(nuevo_equipo)
            db.session.commit()  # Confirmar los cambios en la base de datos

            # Retornar el equipo creado en formato JSON con código 201
            return make_response(EquipoSchema().dump(nuevo_equipo), 201)

        return jsonify({"Mensaje": "Debes ser admin para crear un equipo"}), 403

@equipo_bp.route("/equipos/actualizar", methods=["PUT"])
@jwt_required()
def actualizar_equipo():
    additional_data = get_jwt()
    administrador = additional_data.get("administrador", False)

    if not administrador:
        return jsonify({"Mensaje": "No tiene permisos para actualizar un equipo."}), 403

    data = request.get_json()
    equipo_id = data.get("id")
    equipo = Equipo.query.get_or_404(equipo_id)

    # Validar el valor de 'activo' (0 o 1)
    if 'activo' in data and data['activo'] not in [0, 1]:
        return jsonify({"Mensaje": "El valor de 'activo' debe ser 0 o 1."}), 400

    equipo.nombre = data.get("nombre", equipo.nombre)
    equipo.modelo_id = data.get("modelo_id", equipo.modelo_id)
    equipo.categoria_id = data.get("categoria_id", equipo.categoria_id)
    equipo.costo = data.get("costo", equipo.costo)
    equipo.stock_id = data.get("stock_id", equipo.stock_id)
    equipo.marca_id = data.get("marca_id", equipo.marca_id)
    equipo.activo = data.get("activo", equipo.activo)  # Actualizar solo si se pasa un valor válido
    
    db.session.commit()
    return make_response(EquipoSchema().dump(equipo), 200)

@equipo_bp.route("/equipos/eliminar", methods=["DELETE"])
@jwt_required()
def eliminar_equipo():
    additional_data = get_jwt()
    administrador = additional_data.get("administrador", False)

    if not administrador:
        return jsonify({"Mensaje": "No tiene permisos para eliminar un equipo."}), 403

    equipo_id = request.json.get("id")
    if not equipo_id:
        return jsonify({"Mensaje": "Falta el parámetro 'id' en la solicitud."}), 400

    equipo = Equipo.query.get_or_404(equipo_id)
    equipo.activo = False  # Marcar el equipo como inactivo
    db.session.commit()
    return jsonify({"Mensaje": "Equipo marcado como inactivo correctamente."}), 200

templates/editar_equipo.html
{% extends "template_base.html" %}

{% block title %}Editar Equipo{% endblock %}

{% block content %}
    <h1 class="text-black-50 font-weight-bold">Editar Equipo</h1>
    <form action="{{ url_for('equipo.editar_equipo', id=equipo.id) }}" method="POST">
    
        <div class="text-black-50 font-weight-bold">
            <label for="nombre" class="form-label">Nombre:</label>
            <input type="text" id="nombre" name="nombre" class="form-control" value="{{ equipo.nombre }}" required>
        </div>

        <div class="text-black-50 font-weight-bold">
            <label for="modelo_id" class="form-label">Modelo:</label>
            <select id="modelo_id" name="modelo_id" class="form-select">
                {% for modelo in modelos %}
                    <option value="{{ modelo.id }}" {% if modelo.id == equipo.modelo_id %}selected{% endif %}>{{ modelo.nombre }}</option>
                {% endfor %}
            </select>
        </div>

        <div class="text-black-50 font-weight-bold">
            <label for="categoria_id" class="form-label">Categoría:</label>
            <select id="categoria_id" name="categoria_id" class="form-select">
                {% for categoria in categorias %}
                    <option value="{{ categoria.id }}" {% if categoria.id == equipo.categoria_id %}selected{% endif %}>{{ categoria.nombre }}</option>
                {% endfor %}
            </select>
        </div>

        <div class="text-black-50 font-weight-bold">
            <label for="marca_id" class="form-label">Marca:</label>
            <select id="marca_id" name="marca_id" class="form-select">
                {% for marca in marcas %}
                    <option value="{{ marca.id }}" {% if marca.id == equipo.marca_id %}selected{% endif %}>{{ marca.nombre }}</option>
                {% endfor %}
            </select>
        </div>

        <div class="text-black-50 font-weight-bold">
            <label for="costo" class="form-label">Costo:</label>
            <input type="number" step="0.01" id="costo" name="costo" class="form-control" value="{{ equipo.costo }}" required>
        </div>

        <div class="text-black-50 font-weight-bold">
            <label for="stock_id" class="form-label">Stock:</label>
            <select id="stock_id" name="stock_id" class="form-select">
                {% for stock in stocks %}
                    <option value="{{ stock.id }}" {% if stock.id == equipo.stock_id %}selected{% endif %}>{{ stock.cantidad }}</option>
                {% endfor %}
            </select>
        </div>

        <button type="submit" class="btn btn-primary">Guardar</button>
    </form>
{% endblock %}

templates/editar_proveedores.html
{% extends "template_base.html" %}

{% block content %}
    <h1 class="text-black-50 font-weight-bold">Editar Proveedor</h1>
    
    <form action="{{ url_for('proveedor.editar_proveedor', id=proveedor.id) }}" method="post">
        <div class="form-group">
            <label for="nombre">Nombre del Proveedor:</label>
            <input type="text" id="nombre" name="nombre" class="form-control" value="{{ proveedor.nombre }}" required>
        </div>
        <div class="form-group">
            <label for="contacto">Contacto:</label>
            <input type="text" id="contacto" name="contacto" class="form-control" value="{{ proveedor.contacto }}">
        </div>
        <button type="submit" class="btn btn-primary">Guardar Cambios</button>
    </form>
{% endblock %}

templates/index.html
{% extends "template_base.html" %}

{% block title %}Equipos en Stock{% endblock %}

{% block content %}
    <h1 class="text-black-50 font-weight-bold">Equipos en Stock</h1>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Modelo</th>
                <th>Categoria</th>
                <th>Marca</th>
                <th>Costo</th>
                <th>Stock</th>
            </tr>
        </thead>
        <tbody>
            {% for equipo in equipos %}
                <tr>
                    <td>{{ equipo.modelo_relacionado.nombre }}</td>
                    <td>{{ equipo.categoria_relacionado.nombre }}</td>
                    <td>{{ equipo.marca_relacionado.nombre }}</td>
                    <td>{{ equipo.costo }}</td>
                    <td>{{ equipo.stock_relacionado.cantidad }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    
{% endblock %}

templates/listar_equipos.html
{% extends "template_base.html" %}

{% block title %}Listar Equipos{% endblock %}

{% block content %}
<h1 class="text-black-50 font-weight-bold">Listado de Equipos</h1>
<a href="{{ url_for('equipo.nuevo_equipo') }}" class="btn btn-success mb-3">Agregar Nuevo Equipo</a>
<table class="table table-striped">
    <thead>
        <tr>
            <th>Nombre</th>
            <th>Modelo</th>
            <th>Categoría</th>
            <th>Costo</th>
            <th>Stock</th>
            <th>Marca</th>
            <th>Características</th>
            <th>Acciones</th>
        </tr>
    </thead>
    <tbody>
        {% for equipo in equipos %}
            <tr>
                <td>{{ equipo.nombre }}</td>
                <td>{{ equipo.modelo_relacionado.nombre }}</td>
                <td>{{ equipo.categoria_relacionado.nombre }}</td>
                <td>{{ equipo.costo }}</td>
                <td>{{ equipo.stock_relacionado.cantidad }}</td>
                <td>{{ equipo.marca_relacionado.nombre }}</td>
                <td>
                    <!-- Listar las características asociadas -->
                    {% for caracteristica in equipo.caracteristicas %}
                        <span class="badge badge-info">{{ caracteristica.nombre }}</span>
                    {% endfor %}
                </td>
                <td>
                    <!-- Botón para eliminar -->
                    <form action="{{ url_for('equipo.eliminar_equipo', id=equipo.id) }}" method="post" style="display:inline;">
                        <button class="btn btn-danger btn-sm" type="submit" onclick="return confirm('¿Estás seguro de que quieres eliminar este equipo?');">Eliminar</button>
                    </form>
                    <!-- Botón para editar -->
                    <a href="{{ url_for('equipo.editar_equipo', id=equipo.id) }}" class="btn btn-warning btn-sm">Editar</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

templates/login.html
{% extends "template_base.html" %}

{% block title %}Iniciar Sesión{% endblock %}

{% block content %}
<div class="container mt-5">
    <h2 class="text-center">Iniciar Sesión</h2>
    <form method="POST" action="{{ url_for('auth.login') }}">
        <div class="form-group">
            <label for="username">Nombre de Usuario:</label>
            <input type="text" class="form-control" id="username" name="username" required>
        </div>
        <div class="form-group">
            <label for="password">Contraseña:</label>
            <input type="password" class="form-control" id="password" name="password" required>
        </div>
        <button type="submit" class="btn btn-primary">Iniciar Sesión</button>
        <p class="mt-3">¿No tienes una cuenta? <a href="{{ url_for('auth.users') }}">Regístrate aquí</a></p>
    </form>
    <!-- <script>
        function login() {
            const username = document.getElementById('username').value;
            const password = document.getElementById('password').value;
            
            fetch('/login', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json'
                },
                body: JSON.stringify({ username, password })
            })
            .then(response => response.json())
            .then(data => console.log(data))
            .catch(error => console.error('Error:', error));
        }
    </script> -->
</div>
{% endblock %}

templates/marcas.html
{% extends "template_base.html" %}

{% block title %}Marcas{% endblock %}

{% block content %}
    <h1 class="text-black-50 font-weight-bold">Marcas</h1>
    <p class="text-secondary font-weight-bold">Gestiona las marcas en el sistema.</p>
    
    <!-- Botón para agregar una nueva marca -->
    <a href="{{ url_for('marca.nuevo_marca') }}" class="btn btn-primary mb-3">Agregar Marca</a>
    
    <!-- Tabla para mostrar las marcas -->
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>ID</th>
                <th>Nombre</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
            {% for marca in marcas %}
            <tr>
                <td>{{ marca.id }}</td>
                <td>{{ marca.nombre }}</td>
                <td>
                    <a href="{{ url_for('marca.editar_marca', id=marca.id) }}" class="btn btn-warning btn-sm">Editar</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

templates/modelos_por_marca.html
{% extends "template_base.html" %}

{% block title %}Modelos de {{ marca.nombre }}{% endblock %}

{% block content %}
    <h1 class="text-black-50 font-weight-bold">Modelos de {{ marca.nombre }}</h1>
    
    <!-- Tabla para mostrar los modelos -->
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>ID</th>
                <th>Nombre</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
            {% for modelo in modelos %}
            <tr>
                <td>{{ modelo.id }}</td>
                <td>{{ modelo.nombre }}</td>
                <td>
                    <!-- Aquí puedes agregar botones para editar o eliminar los modelos si es necesario -->
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

templates/nuevo_accesorio.html
{% extends "template_base.html" %}

{% block content %}
    <h1 class="text-black-50 font-weight-bold">Agregar Nuevo Accesorio</h1>
    
    <form action="{{ url_for('accesorio.nuevo_accesorio') }}" method="post">
        <div class="form-group">
            <label for="tipo">Tipo:</label>
            <input type="text" id="tipo" name="tipo" class="form-control" required>
        </div>
        <div class="form-group">
            <label for="compatible_con">Compatibilidad:</label>
            <input type="text" id="compatible_con" name="compatible_con" class="form-control">
        </div>
        <div class="form-group">
            <label for="proveedor">Proveedor:</label>
            <select id="proveedor" name="proveedor" class="form-control" required>
                {% for proveedor in proveedores %}
                    <option value="{{ proveedor.id }}">{{ proveedor.nombre }}</option>
                {% endfor %}
            </select>
        </div>
        <button type="submit" class="btn btn-primary">Agregar</button>
    </form>
{% endblock %}

templates/nuevo_equipo.html
{% extends "template_base.html" %}

{% block title %}Nuevo Equipo{% endblock %}

{% block content %}
<h1 class="text-black-50 font-weight-bold">Agregar Nuevo Equipo</h1>
<form action="/equipo/nuevo" method="POST">
    <div class="form-group">
        <label for="nombre">Nombre:</label>
        <input type="text" class="form-control" id="nombre" name="nombre" required>
    </div>

    <div class="form-group">
        <label for="modelo_id">Modelo:</label>
        <select class="form-control" id="modelo_id" name="modelo_id" required>
            <option value="" disabled selected>Seleccionar Modelo</option>
            {% for modelo in modelos %}
            <option value="{{ modelo.id }}">{{ modelo.nombre }}</option>
            {% endfor %}
        </select>
    </div>

    <div class="form-group">
        <label for="categoria_id">Categoría:</label>
        <select class="form-control" id="categoria_id" name="categoria_id" required>
            <option value="" disabled selected>Seleccionar Categoría</option>
            {% for categoria in categorias %}
            <option value="{{ categoria.id }}">{{ categoria.nombre }}</option>
            {% endfor %}
        </select>
    </div>

    <div class="form-group">
        <label for="marca_id">Marca:</label>
        <select class="form-control" id="marca_id" name="marca_id" required>
            <option value="" disabled selected>Seleccionar Marca</option>
            {% for marca in marcas %}
            <option value="{{ marca.id }}">{{ marca.nombre }}</option>
            {% endfor %}
        </select>
    </div>

    <div class="form-group">
        <label for="costo">Costo:</label>
        <input type="number" step="0.01" class="form-control" id="costo" name="costo" required>
    </div>

    <div class="form-group">
        <label for="stock_id">Stock:</label>
        <select class="form-control" id="stock_id" name="stock_id" required>
            <option value="" disabled selected>Seleccionar Stock</option>
            {% for stock in stocks %}
            <option value="{{ stock.id }}">{{ stock.cantidad }}</option>
            {% endfor %}
        </select>
    </div>

    <button type="submit" class="btn btn-primary">Agregar</button>
    <a href="/equipos" class="btn btn-secondary">Cancelar</a>
</form>
{% endblock %}

templates/nuevo_marca.html
{% extends "template_base.html" %}

{% block title %}Agregar Marca{% endblock %}

{% block content %}
    <h1 class="text-black-50 font-weight-bold">Agregar Marca</h1>

    <form action="{{ url_for('marca.nuevo_marca') }}" method="post">
        <div class="form-group">
            <label for="nombre">Nombre:</label>
            <input type="text" id="nombre" name="nombre" class="form-control" required>
        </div>
        <button type="submit" class="btn btn-primary">Agregar Marca</button>
    </form>

    {% if error %}
        <div class="alert alert-danger mt-3">
            {{ error }}
        </div>
    {% endif %}
{% endblock %}

templates/nuevo_modelo.html
{% extends "template_base.html" %}

{% block title %}Agregar Modelo{% endblock %}

{% block content %}
    <h1 class="text-black-50 font-weight-bold">Agregar Modelo</h1>

    <form action="{{ url_for('modelo.nuevo_modelo') }}" method="post">
        <div class="form-group">
            <label for="nombre">Nombre:</label>
            <input type="text" id="nombre" name="nombre" class="form-control" required>
        </div>
        
        <div class="form-group">
            <label for="fabricante_id">Fabricante:</label>
            <select id="fabricante_id" name="fabricante_id" class="form-control" required>
                <option value="">Seleccionar Fabricante</option>
                {% for fabricante in fabricantes %}
                    <option value="{{ fabricante.id }}">{{ fabricante.nombre }}</option>
                {% endfor %}
            </select>
        </div>
        
        <div class="form-group">
            <label for="marca_id">Marca:</label>
            <select id="marca_id" name="marca_id" class="form-control" required>
                <option value="">Seleccionar Marca</option>
                {% for marca in marcas %}
                    <option value="{{ marca.id }}">{{ marca.nombre }}</option>
                {% endfor %}
            </select>
        </div>
        
        <button type="submit" class="btn btn-primary">Agregar Modelo</button>
    </form>

    {% if error %}
        <div class="alert alert-danger mt-3">
            {{ error }}
        </div>
    {% endif %}
{% endblock %}

templates/nuevo_proveedores.html
{% extends "template_base.html" %}

{% block title %}Agregar proveedores{% endblock %}

{% block content %}
    <h1 class="text-black-50 font-weight-bold">Agregar Proveedor</h1>
    
    <form action="{{ url_for('proveedor.nuevo_proveedor') }}" method="post">
        <div class="form-group">
            <label for="nombre">Nombre del Proveedor:</label>
            <input type="text" id="nombre" name="nombre" class="form-control" required>
        </div>
        <div class="form-group">
            <label for="contacto">Contacto:</label>
            <input type="text" id="contacto" name="contacto" class="form-control">
        </div>
        <button type="submit" class="btn btn-primary">Agregar</button>
    </form>
    {% if error %}
        <div class="alert alert-danger mt-3">
            {{ error }}
        </div>
    {% endif %}
{% endblock %}

templates/registro.html
{% extends "template_base.html" %}

{% block title %}Registrarse{% endblock %}

{% block content %}
    <h1>Registrarse</h1>
    <form method="POST">
        {{ form.hidden_tag() }}
        <div class="form-group">
            <label for="email">Correo Electrónico</label>
            {{ form.email(class="form-control") }}
        </div>
        <div class="form-group">
            <label for="password">Contraseña</label>
            {{ form.password(class="form-control") }}
        </div>
        <button type="submit" class="btn btn-primary">Registrarse</button>
        <a href="{{ url_for('auth.login') }}">Iniciar Sesión</a>
    </form>
{% endblock %}

templates/template_base.html
<!doctype html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}PhoneZone{% endblock %}</title>
    <!-- Bootstrap CSS -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <!-- CSS personalizado -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
</head>

<body class="d-flex flex-column min-vh-100">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand text-warning" href="/">PhoneZone</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav mr-auto">
                <!-- Menú desplegable -->
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle btn btn-warning text-dark font-weight-bold mx-1" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Categorías
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item text-primary" href="/equipos">Equipos</a>
                        <a class="dropdown-item text-primary" href="/fabricantes">Fabricantes</a>
                        <a class="dropdown-item text-primary" href="/marcas">Marcas</a>
                        <a class="dropdown-item text-primary" href="/modelos">Modelos</a>
                        <a class="dropdown-item text-primary" href="/caracteristicas">Características</a>
                        <a class="dropdown-item text-primary" href="/proveedores">Proveedores</a>
                        <a class="dropdown-item text-primary" href="/accesorios">Accesorios</a>
                    </div>
                </li>
            </ul>
            <!-- Logo a la derecha -->
            <a class="navbar-brand" href="#">
                <img src="{{ url_for('static', filename='img/logo.png') }}" alt="Logo" style="height: 40px;">
            </a>
        </div>
    </nav>

    <div class="container mt-4 text-light flex-grow-1">
        {% block content %}{% endblock %}
    </div>

    <footer class="footer bg-dark text-white py-4 mt-auto">
        <div class="container text-center">
            <span>&copy; 2024 Venta de celulares. Desarrollado por Victorio Octavio y Druetta Cristian.Todos los derechos reservados.</span>
        </div>
    </footer>

    <!-- JavaScript dependencies -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.3/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <!-- JavaScript personalizado -->
    <script src="{{ url_for('static', filename='js/script.js') }}"></script>
</body>
</html>